name: Ping Render Service

on:
  schedule:
    - cron: "*/5 * * * *"   # Cada 5 minutos
  workflow_dispatch:        # Permite ejecutarlo manualmente tambi√©n

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ejecutar GET request a Render
      - run: |
          echo "Realizando ping a Render..."
          curl -I https://rewardshub-vvaj.onrender.com/
